language: objective-c
os:
  - osx
compiler:
  - clang
before_install: ./travis/travis-dependencies.sh
install:
  - wget https://www.dropbox.com/s/4dkkw6h6v2ubuuo/pspsdk_v2.tar.gz
  - tar -vzxf pspsdk_v2.tar.gz
script: ./travis/travis-build.sh
